_wandb:
    value:
        cli_version: 0.22.2
        e:
            y31kf2l2wsb13xryrf8i7mpr3kq0gec1:
                cpu_count: 128
                cpu_count_logical: 256
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "105089261568"
                        used: "40683814912"
                email: luca.callisti@gmail.com
                executable: /scratch/callisti/Thesis-enc/bin/python
                git:
                    commit: ce83db19fec87c2a938a36c9901f87cd1e031bc0
                    remote: https://github.com/LucaCallisti/SME_for_Adam_and_RMSProp
                gpu: NVIDIA A40
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-c6e4e89a-7137-3de8-14e1-e85221bc5037
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-3b32eed9-bc25-7c40-d7f5-9f11e5982271
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-118c75b9-d454-64bb-34a5-4f0feb384b45
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-b97d8c95-9042-7d4c-244e-40e4c7070b86
                host: gpu03
                memory:
                    total: "2151617064960"
                os: Linux-5.15.0-161-generic-x86_64-with-glibc2.17
                program: -m NeuralNetwork.main_v3
                python: CPython 3.8.20
                root: /data/home/callisti/Thesis/Code_2025-11-22
                slurm:
                    cluster_name: toeplitz
                    conf: /etc/slurm/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x0000000000000000000000000000000100000000000000000000000000000001
                    cpu_bind_list: 0x0000000000000000000000000000000100000000000000000000000000000001
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "2"
                    distribution: cyclic
                    gtids: "0"
                    job_cpus_per_node: "2"
                    job_gid: "1069"
                    job_id: "20039"
                    job_name: python
                    job_nodelist: gpu03
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_uid: "1069"
                    job_user: callisti
                    jobid: "20039"
                    launch_node_ipaddr: 10.0.10.254
                    localid: "0"
                    mpi_type: pmi2
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gpu03
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "37817"
                    pty_win_col: "145"
                    pty_win_row: "18"
                    srun_comm_host: 10.0.10.254
                    srun_comm_port: "45523"
                    step_id: "0"
                    step_launcher_port: "45523"
                    step_nodelist: gpu03
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /data/home/callisti/Thesis/Code_2025-11-22
                    submit_host: toeplitz.cs.dm.unipi.it
                    task_pid: "119563"
                    tasks_per_node: "1"
                    topology_addr: gpu03
                    topology_addr_pattern: node
                    umask: "0002"
                    working_cluster: toeplitz:toeplitz:6817:9472:109
                startedAt: "2025-11-24T11:04:26.815463Z"
                writerId: y31kf2l2wsb13xryrf8i7mpr3kq0gec1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 13
            "4": 3.8.20
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
