_wandb:
    value:
        cli_version: 0.23.0
        e:
            cs6w7qbt6bqdlzxndniskfwgg96g963g:
                cpu_count: 20
                cpu_count_logical: 28
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1023146979328"
                        used: "260637949952"
                email: luca.callisti@gmail.com
                executable: C:\Users\lucac\Desktop\Python Enviroments\Thesis\Scripts\python.exe
                git:
                    commit: eab4d31fe04a439686eebfc5a1d6388ab3ad3771
                    remote: https://github.com/LucaCallisti/SME_for_Adam_and_RMSProp
                gpu: NVIDIA GeForce RTX 4060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060
                      uuid: GPU-0ea9b46e-3905-fc05-3717-e6e44b220f6c
                host: PCRetis
                memory:
                    total: "34100047872"
                os: Windows-11-10.0.26100-SP0
                program: -m Poly.main
                python: CPython 3.13.9
                root: C:\Users\lucac\Desktop\Codice\SME_for_Adam_and_RMSProp\Thesis\Code_2025-11-22
                startedAt: "2025-11-24T10:00:33.234595Z"
                writerId: cs6w7qbt6bqdlzxndniskfwgg96g963g
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.9
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
batch_size:
    value: 1024
c:
    value: 0.5
c_1:
    value: 1
c_2:
    value: 0.5
device:
    value: cpu
epsilon:
    value: 0.1
final_time:
    value: 10
num_runs:
    value: 1024
optimizer:
    value: RMSProp
points:
    value:
        - -1
        - 1
        - 0.25
        - 2
regime:
    value: balistic
results_dir:
    value: results
seed_1st:
    value: 150
seed_2nd:
    value: 200
seed_disc:
    value: 100
seed_noise:
    value: 25
seed_parameters:
    value: 50
sigma_list:
    value:
        - 0.2
simulations:
    value:
        - 1st_order_sde
        - 2nd_order_sde
skip_initial_point:
    value: 2
tau_list:
    value:
        - 0.05
verbose:
    value: true
wandb:
    value: true
